name: Verificar conflictos y borrar rama

on:
  pull_request:
    branches:
      - main  # Solo se ejecuta si el PR va dirigido a 'main'

jobs:
  merge-check:
    runs-on: ubuntu-latest

    steps:
      - name: Definir nombre de la rama actual
        run: echo "SOURCE_BRANCH=${GITHUB_HEAD_REF}" >> $GITHUB_ENV

      - name: Clonar el repositorio con historial completo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Necesario para poder hacer merge con otras ramas

      - name: Obtener todas las ramas
        run: git fetch --all

      - name: Posicionarse en main y crear rama temporal
        run: |
          git checkout main
          git checkout -b test-merge

      - name: Intentar hacer merge con la rama del PR
        run: |
          echo "Intentando hacer merge con $SOURCE_BRANCH"
          git merge origin/${SOURCE_BRANCH} --no-commit --no-ff

      - name: Borrar la rama si no hay conflictos
        if: success()
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo "No hay conflictos. Eliminando la rama ${SOURCE_BRANCH}"
          curl -X DELETE -H "Authorization: token $GH_PAT" \
            https://api.github.com/repos/${{ github.repository }}/git/refs/heads/${SOURCE_BRANCH}

      - name: Falla en caso de conflictos
        if: failure()
        run: |
          echo "❌ Conflictos detectados al hacer merge de '${SOURCE_BRANCH}' con 'main'"
          exit 1
